Repository Oncognier/cogroom-be, pull requests merged in 2025-06, with the labels that each got.

#20 [FEAT] 스트릭 기록 일괄 업데이트(초기화) 구현
  src/main/java/oncog/cogroom/domain/content/entity/ContentMember.java
  src/main/java/oncog/cogroom/domain/daily/entity/AssignedQuestion.java
  src/main/java/oncog/cogroom/domain/member/entity/Member.java
  src/main/java/oncog/cogroom/domain/notice/entity/Notice.java
  src/main/java/oncog/cogroom/domain/streak/entity/Streak.java
  src/main/java/oncog/cogroom/domain/streak/repository/StreakLogRepository.java
  src/main/java/oncog/cogroom/domain/streak/repository/StreakRepository.java
  src/main/java/oncog/cogroom/domain/streak/scheduler/StreakSchduler.java
  src/main/java/oncog/cogroom/domain/streak/service/StreakService.java
Labels: 🚀 feature

#28 [FEAT] 사용자 정보 설정 API 구현 및 S3 API 구현
  build.gradle
  src/main/java/oncog/cogroom/domain/member/controller/memberController.java
  src/main/java/oncog/cogroom/domain/member/dto/MemberRequestDTO.java
  src/main/java/oncog/cogroom/domain/member/dto/MemberResponseDTO.java
  src/main/java/oncog/cogroom/domain/member/entity/Member.java
  src/main/java/oncog/cogroom/domain/member/repository/MemberRepository.java
  src/main/java/oncog/cogroom/domain/member/service/MemberService.java
  src/main/java/oncog/cogroom/global/config/S3Config.java
  src/main/java/oncog/cogroom/global/config/SecurityConfig.java
  src/main/java/oncog/cogroom/global/s3/controller/S3Controller.java
  src/main/java/oncog/cogroom/global/s3/dto/S3RequestDTO.java
  src/main/java/oncog/cogroom/global/s3/service/S3Service.java
  src/main/java/oncog/cogroom/global/security/jwt/JwtProvider.java
  src/main/resources/application.yml
Labels: 🚀 feature

#33 [REFACTOR] createdBy, updatedBy BaseEntity 설정
  src/main/java/oncog/cogroom/domain/content/entity/Content.java
  src/main/java/oncog/cogroom/domain/daily/entity/Question.java
  src/main/java/oncog/cogroom/domain/notice/entity/Notice.java
  src/main/java/oncog/cogroom/global/common/entity/BaseEntity.java
  src/main/java/oncog/cogroom/global/config/AuditorAwareConfig.java
Labels: ♻️refactor

#35 [REFACTOR] 데일리 질문 조회 에러 처리 및 코드 리팩토링
  src/main/java/oncog/cogroom/domain/daily/controller/DailyController.java
  src/main/java/oncog/cogroom/domain/daily/dto/response/DailyQuestionResponseDTO.java
  src/main/java/oncog/cogroom/domain/daily/exception/DailyErrorCode.java
  src/main/java/oncog/cogroom/domain/daily/service/DailyService.java
  src/main/java/oncog/cogroom/domain/member/service/MemberService.java
  src/main/java/oncog/cogroom/domain/streak/controller/StreakController.java
  src/main/java/oncog/cogroom/domain/streak/docs/StreakControllerDocs.java
  src/main/java/oncog/cogroom/domain/streak/dto/response/StreakCalenderResponseDTO.java
  src/main/java/oncog/cogroom/domain/streak/service/StreakService.java
  src/main/java/oncog/cogroom/global/common/service/BaseService.java
  src/main/java/oncog/cogroom/global/exception/domain/DailyException.java
  src/main/java/oncog/cogroom/global/security/jwt/JwtProvider.java
Labels: ♻️refactor

#43 [FEAT] 데일리 답변 등록 및 수정 API 구현
  src/main/java/oncog/cogroom/domain/daily/controller/DailyController.java
  src/main/java/oncog/cogroom/domain/daily/controller/docs/DailyControllerDocs.java
  src/main/java/oncog/cogroom/domain/daily/dto/request/DailyAnswerRequestDTO.java
  src/main/java/oncog/cogroom/domain/daily/entity/Answer.java
  src/main/java/oncog/cogroom/domain/daily/entity/AssignedQuestion.java
  src/main/java/oncog/cogroom/domain/daily/entity/QuestionCategory.java
  src/main/java/oncog/cogroom/domain/daily/exception/DailyErrorCode.java
  src/main/java/oncog/cogroom/domain/daily/respository/AnswerRepository.java
  src/main/java/oncog/cogroom/domain/daily/respository/AssignedQuestionRepository.java
  src/main/java/oncog/cogroom/domain/daily/service/DailyService.java
  src/main/java/oncog/cogroom/domain/member/service/MemberService.java
  src/main/java/oncog/cogroom/domain/streak/docs/StreakControllerDocs.java
  src/main/java/oncog/cogroom/domain/streak/entity/StreakLog.java
  src/main/java/oncog/cogroom/domain/streak/repository/StreakLogRepository.java
  src/main/java/oncog/cogroom/domain/streak/repository/StreakRepository.java
  src/main/java/oncog/cogroom/domain/streak/service/StreakService.java
  src/main/java/oncog/cogroom/global/common/service/BaseService.java
  src/main/java/oncog/cogroom/global/security/jwt/JwtProvider.java
  src/main/java/oncog/cogroom/global/security/service/CustomUserDetailService.java
Labels: 🚀 feature

#42 [REFACTOR] authController, MemberController 스웨거 예외 응답 추가
  src/main/java/oncog/cogroom/domain/auth/controller/AuthController.java
  src/main/java/oncog/cogroom/domain/auth/docs/AuthControllerDocs.java
  src/main/java/oncog/cogroom/domain/member/controller/MemberController.java
  src/main/java/oncog/cogroom/domain/member/docs/MemberControllerDocs.java
Labels: ♻️refactor

#48 [FEAT] healthCheck API 구현
  src/main/java/oncog/cogroom/global/config/SecurityConfig.java
  src/main/java/oncog/cogroom/global/s3/controller/LoadBalancerController.java
Labels: ♻️refactor

#51 [REFACTOR] daily 메서드 오타 수정 및 누락 메서드 설정, 로직 추가
  src/main/java/oncog/cogroom/domain/auth/controller/AuthController.java
  src/main/java/oncog/cogroom/domain/daily/controller/docs/DailyControllerDocs.java
  src/main/java/oncog/cogroom/domain/daily/dto/request/DailyAnswerRequestDTO.java
  src/main/java/oncog/cogroom/domain/daily/dto/response/DailyQuestionResponseDTO.java
  src/main/java/oncog/cogroom/domain/daily/exception/DailyErrorCode.java
  src/main/java/oncog/cogroom/domain/daily/respository/AssignedQuestionRepository.java
  src/main/java/oncog/cogroom/domain/daily/service/DailyQuestionAssignService.java
  src/main/java/oncog/cogroom/domain/daily/service/DailyService.java
  src/main/java/oncog/cogroom/domain/streak/controller/StreakController.java
  src/main/java/oncog/cogroom/domain/streak/docs/StreakControllerDocs.java
  src/main/java/oncog/cogroom/domain/streak/dto/response/StreakCalendarResponseDTO.java
  src/main/java/oncog/cogroom/domain/streak/service/StreakService.java
  src/main/java/oncog/cogroom/global/exception/GlobalExceptionHandler.java
Labels: 🚀 feature, ♻️refactor

#57 [REFACTOR] 이메일 인증 상태 검사 API 추가 및 에러 코드 리팩토링
  src/main/java/oncog/cogroom/domain/auth/controller/AuthController.java
  src/main/java/oncog/cogroom/domain/auth/docs/AuthControllerDocs.java
  src/main/java/oncog/cogroom/domain/auth/exception/AuthErrorCode.java
  src/main/java/oncog/cogroom/domain/auth/repository/EmailRepository.java
  src/main/java/oncog/cogroom/domain/auth/service/EmailService.java
  src/main/java/oncog/cogroom/domain/auth/service/social/AbstractAuthService.java
  src/main/java/oncog/cogroom/domain/auth/service/social/KakaoAuthService.java
  src/main/java/oncog/cogroom/domain/member/dto/MemberRequestDTO.java
  src/main/java/oncog/cogroom/domain/member/service/MemberService.java
  src/main/java/oncog/cogroom/global/exception/GlobalExceptionHandler.java
  src/main/java/oncog/cogroom/global/security/controller/LoadBalancerController.java
Labels: ♻️refactor

#59 [FIX] jwt 토큰 만료 시간 오류 수정
  src/main/java/oncog/cogroom/global/security/jwt/JwtProvider.java
Labels: 🐛bug

#60 [ci/cd] 젠킨스 및 도커 초기 설정
  Dockerfile
  compose.yaml
  docker-compose.yaml
Labels: ⚙️setup

#64 [CICD] docker file 수정
  Dockerfile
  docker-compose.yaml
Labels: ⚙️setup

#78 [FEAT] 홈 콘텐츠 조회 API 구현
  src/main/java/oncog/cogroom/domain/content/controller/ContentController.java
  src/main/java/oncog/cogroom/domain/content/controller/docs/ContentControllerDocs.java
  src/main/java/oncog/cogroom/domain/content/dto/ContentResponseDTO.java
  src/main/java/oncog/cogroom/domain/content/entity/ContentExpectedEffect.java
  src/main/java/oncog/cogroom/domain/content/entity/ContentImage.java
  src/main/java/oncog/cogroom/domain/content/entity/ContentThumbnail.java
  src/main/java/oncog/cogroom/domain/content/exception/ContentErrorCode.java
  src/main/java/oncog/cogroom/domain/content/exception/ContentException.java
  src/main/java/oncog/cogroom/domain/content/repository/ContentImageRepository.java
  src/main/java/oncog/cogroom/domain/content/repository/ContentRepository.java
  src/main/java/oncog/cogroom/domain/content/service/ContentService.java
Labels: 🚀 feature

#83 [REFACTOR] streakUpdateServce, streakService 로직 분리 및 주석 추가, content 엔티티 수정
  src/main/java/oncog/cogroom/domain/content/entity/Content.java
  src/main/java/oncog/cogroom/domain/daily/controller/DailyController.java
  src/main/java/oncog/cogroom/domain/daily/service/DailyQuestionAssignService.java
  src/main/java/oncog/cogroom/domain/daily/service/DailyService.java
  src/main/java/oncog/cogroom/domain/streak/scheduler/StreakSchduler.java
  src/main/java/oncog/cogroom/domain/streak/service/StreakService.java
  src/main/java/oncog/cogroom/domain/streak/service/StreakUpdateService.java
Labels: ♻️refactor

#89 [FEAT] 로그아웃 API 구현
  build.gradle
  src/main/java/oncog/cogroom/domain/auth/controller/AuthController.java
  src/main/java/oncog/cogroom/domain/auth/controller/docs/AuthControllerDocs.java
  src/main/java/oncog/cogroom/domain/auth/exception/AuthErrorCode.java
  src/main/java/oncog/cogroom/domain/auth/service/redis/RedisService.java
  src/main/java/oncog/cogroom/domain/auth/service/session/AuthSessionService.java
  src/main/java/oncog/cogroom/domain/auth/service/social/AbstractAuthService.java
  src/main/java/oncog/cogroom/domain/auth/service/social/KakaoAuthService.java
  src/main/java/oncog/cogroom/global/config/RedisConfig.java
  src/main/java/oncog/cogroom/global/config/SecurityConfig.java
  src/main/java/oncog/cogroom/global/security/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/oncog/cogroom/global/security/jwt/JwtAuthenticationFilter.java
  src/main/java/oncog/cogroom/global/security/jwt/JwtProvider.java
  src/main/resources/application.yml
Labels: 🚀 feature

#95 [FEAT] 마이페이지 데일리 질문 및 답변 조회 API 구현
  src/main/java/oncog/cogroom/domain/auth/service/session/AuthSessionService.java
  src/main/java/oncog/cogroom/domain/daily/dto/response/DailyQuestionResponseDTO.java
  src/main/java/oncog/cogroom/domain/daily/exception/DailyErrorCode.java
  src/main/java/oncog/cogroom/domain/daily/repository/AnswerRepository.java
  src/main/java/oncog/cogroom/domain/daily/repository/AssignedQuestionRepository.java
  src/main/java/oncog/cogroom/domain/daily/repository/QuestionRepository.java
  src/main/java/oncog/cogroom/domain/daily/respository/AssignedQuestionRepository.java
  src/main/java/oncog/cogroom/domain/daily/service/DailyQuestionAssignService.java
  src/main/java/oncog/cogroom/domain/daily/service/DailyService.java
  src/main/java/oncog/cogroom/domain/member/controller/MemberController.java
  src/main/java/oncog/cogroom/domain/member/controller/docs/MemberControllerDocs.java
  src/main/java/oncog/cogroom/domain/member/service/MemberService.java
Labels: 🚀 feature

#99 [FIX] 마이페이지 Q&A 생성자 오류 수정
  src/main/java/oncog/cogroom/domain/daily/dto/response/DailyQuestionResponseDTO.java
Labels: 🚨hotfix

#113 [FEAT] 랜덤 닉네임 생성 API 구현
  src/main/java/oncog/cogroom/domain/auth/service/social/AbstractAuthService.java
Labels: 🚀 feature

#115 [FEAT] 웰컴 메일 발송 API 구현
  src/main/java/oncog/cogroom/domain/auth/controller/AuthController.java
  src/main/java/oncog/cogroom/domain/auth/controller/docs/AuthControllerDocs.java
  src/main/java/oncog/cogroom/domain/auth/dto/request/AuthRequestDTO.java
  src/main/java/oncog/cogroom/domain/auth/dto/response/AuthResponseDTO.java
  src/main/java/oncog/cogroom/domain/auth/service/AuthService.java
  src/main/java/oncog/cogroom/domain/auth/service/AuthServiceRouter.java
  src/main/java/oncog/cogroom/domain/auth/service/EmailService.java
  src/main/java/oncog/cogroom/domain/auth/service/social/AbstractAuthService.java
Labels: 🚀 feature

#120 [FEAT] 어드민 회원 조회 API 구현
  src/main/java/oncog/cogroom/domain/admin/controller/AdminController.java
  src/main/java/oncog/cogroom/domain/admin/dto/request/AdminRequest.java
  src/main/java/oncog/cogroom/domain/admin/dto/response/AdminResponse.java
  src/main/java/oncog/cogroom/domain/admin/dto/response/PageResponse.java
  src/main/java/oncog/cogroom/domain/admin/service/AdminService.java
  src/main/java/oncog/cogroom/domain/auth/service/social/AbstractAuthService.java
  src/main/java/oncog/cogroom/domain/member/repository/MemberRepository.java
  src/main/java/oncog/cogroom/global/common/response/code/ApiErrorCode.java
  src/main/java/oncog/cogroom/global/config/SecurityConfig.java
  src/main/java/oncog/cogroom/global/security/jwt/JwtAccessDeniedHandler.java
Labels: 🚀 feature

#128 [REFACTOR] 사용자 정보 조회 권한 필드 추가 (summary)
  src/main/java/oncog/cogroom/domain/member/dto/response/MemberResponse.java
  src/main/java/oncog/cogroom/domain/member/service/MemberService.java
Labels: ♻️refactor

#130 [REFACTOR] 어드민 회원 목록 조회 응답 값 추가
  src/main/java/oncog/cogroom/domain/admin/dto/response/AdminResponse.java
  src/main/java/oncog/cogroom/global/config/SecurityConfig.java
Labels: ♻️refactor

#132 [REFACTOR] 어드민 사용자 목록 조회 페이징 에러 처리
  src/main/java/oncog/cogroom/domain/admin/exception/AdminErrorCode.java
  src/main/java/oncog/cogroom/domain/admin/service/AdminService.java
  src/main/java/oncog/cogroom/global/common/response/code/ApiErrorCode.java
Labels: ♻️refactor

#140 [REFACTOR] 어드민 데일리 질문 조회 카테고리 리팩토링
  src/main/java/oncog/cogroom/domain/admin/service/AdminDailyService.java
  src/main/java/oncog/cogroom/domain/admin/validator/AdminValidator.java
Labels: ♻️refactor

#141 [FEATURE] 사용자 회원 탈퇴 API 구현
  src/main/java/oncog/cogroom/domain/admin/validator/AdminValidator.java
  src/main/java/oncog/cogroom/domain/auth/controller/AuthController.java
  src/main/java/oncog/cogroom/domain/auth/controller/docs/AuthControllerDocs.java
  src/main/java/oncog/cogroom/domain/auth/dto/request/AuthRequest.java
  src/main/java/oncog/cogroom/domain/auth/service/AuthService.java
  src/main/java/oncog/cogroom/domain/auth/service/AuthServiceRouter.java
  src/main/java/oncog/cogroom/domain/auth/service/TokenService.java
  src/main/java/oncog/cogroom/domain/auth/service/session/AuthSessionService.java
  src/main/java/oncog/cogroom/domain/auth/service/social/AbstractAuthService.java
  src/main/java/oncog/cogroom/domain/auth/service/social/KakaoAuthService.java
  src/main/java/oncog/cogroom/domain/member/event/MembersWithdrawalEventListener.java
  src/main/java/oncog/cogroom/domain/member/service/MemberService.java
  src/main/resources/application.yml
Labels: 🚀 feature
