Repository Oncognier/cogroom-be, pull requests merged in 2025-07, with the labels that each got.

#143 [REFACTOR] 데일리 질문 등록/수정 에러코드 수정
  src/main/java/oncog/cogroom/domain/daily/controller/docs/DailyControllerDocs.java
  src/main/java/oncog/cogroom/domain/daily/dto/request/DailyRequest.java
  src/main/java/oncog/cogroom/domain/daily/exception/DailyErrorCode.java
Labels: ♻️refactor

#147 [REFACTOR] 사용자 정보 수정 에러 수정
  src/main/java/oncog/cogroom/domain/auth/entity/EmailVerification.java
  src/main/java/oncog/cogroom/domain/auth/repository/EmailRepository.java
  src/main/java/oncog/cogroom/domain/auth/service/EmailService.java
  src/main/java/oncog/cogroom/domain/member/scheduler/MemberScheduler.java
Labels: ♻️refactor

#149 [REFACTOR] 이메일 인증 및 웰컴 이메일 페이지 적용
  build.gradle
  src/main/java/oncog/cogroom/domain/auth/controller/AuthController.java
  src/main/java/oncog/cogroom/domain/auth/controller/docs/AuthControllerDocs.java
  src/main/java/oncog/cogroom/domain/auth/service/EmailService.java
  src/main/resources/templates/email-page.html
  src/main/resources/templates/welcome-page.html
Labels: ♻️refactor

#154 [REFACTOR] 프론트 스테이지 url cors 설정
  src/main/java/oncog/cogroom/global/config/SecurityConfig.java
Labels: ♻️refactor

#158 [FIX] 사용자 정보 수정 profileUrl null 에러처리
  src/main/java/oncog/cogroom/domain/member/service/MemberService.java
Labels: ♻️refactor

#163 [REFACTOR] 이메일 인증 상태 반환 API 수정
  src/main/java/oncog/cogroom/domain/auth/controller/AuthController.java
  src/main/java/oncog/cogroom/domain/auth/controller/docs/AuthControllerDocs.java
  src/main/java/oncog/cogroom/domain/auth/service/EmailService.java
  src/main/java/oncog/cogroom/global/config/SecurityConfig.java
  src/main/java/oncog/cogroom/global/config/SwaggerConfig.java
Labels: ♻️refactor

#168 [REFACTOR] 로그인 API 수정(재로그인 상황)
  src/main/java/oncog/cogroom/domain/auth/service/social/AbstractAuthService.java
  src/main/java/oncog/cogroom/domain/member/entity/Member.java
Labels: ♻️refactor

#172 [FEAT] prometheus 모니터링 설정
  build.gradle
  src/main/java/oncog/cogroom/domain/member/scheduler/MemberScheduler.java
  src/main/resources/application.yml
Labels: 🚀 feature

#173 [REFACTOR] .yml 추적 제외 파일 다시 포함
  .gitignore
  src/main/java/oncog/cogroom/global/infra/prometheus/alertmanager.yml
  src/main/java/oncog/cogroom/global/infra/prometheus/prometheus.yml
  src/main/java/oncog/cogroom/global/infra/prometheus/rules.yml
Labels: ♻️refactor

#174 [REFACTOR] 데일리 질문 할당 로직 리팩토링 및 배치 적용
  build.gradle
  src/main/java/oncog/cogroom/domain/daily/batch/DailyBatchConfig.java
  src/main/java/oncog/cogroom/domain/daily/batch/DailyQuestionAssignBatchConfig.java
  src/main/java/oncog/cogroom/domain/daily/batch/DailyQuestionAssignProcessor.java
  src/main/java/oncog/cogroom/domain/daily/scheduler/DailyQuestionAssignBatchSchduler.java
  src/main/java/oncog/cogroom/domain/daily/scheduler/DailyQuestionAssignSchduler.java
  src/main/java/oncog/cogroom/domain/daily/service/DailyQuestionAssignService.java
  src/main/java/oncog/cogroom/domain/member/repository/MemberRepository.java
  src/main/java/oncog/cogroom/global/common/batch/logging/BatchJobLogger.java
  src/main/java/oncog/cogroom/global/common/batch/repository/BatchJobExecutionNativeRepository.java
  src/main/java/oncog/cogroom/global/common/batch/repository/BatchJobExecutionNativeRepositoryImpl.java
  src/main/java/oncog/cogroom/global/config/ShedLockConfig.java
  src/main/resources/application.yml
Labels: ♻️refactor

#178 [RELEASE] v0.1.0 배포
  .gitignore
  build.gradle
  src/main/java/oncog/cogroom/domain/auth/service/social/AbstractAuthService.java
  src/main/java/oncog/cogroom/domain/daily/batch/DailyBatchConfig.java
  src/main/java/oncog/cogroom/domain/daily/batch/DailyQuestionAssignBatchConfig.java
  src/main/java/oncog/cogroom/domain/daily/batch/DailyQuestionAssignProcessor.java
  src/main/java/oncog/cogroom/domain/daily/scheduler/DailyQuestionAssignBatchSchduler.java
  src/main/java/oncog/cogroom/domain/daily/scheduler/DailyQuestionAssignSchduler.java
  src/main/java/oncog/cogroom/domain/daily/service/DailyQuestionAssignService.java
  src/main/java/oncog/cogroom/domain/member/entity/Member.java
  src/main/java/oncog/cogroom/domain/member/repository/MemberRepository.java
  src/main/java/oncog/cogroom/global/common/batch/logging/BatchJobLogger.java
  src/main/java/oncog/cogroom/global/common/batch/repository/BatchJobExecutionNativeRepository.java
  src/main/java/oncog/cogroom/global/common/batch/repository/BatchJobExecutionNativeRepositoryImpl.java
  src/main/java/oncog/cogroom/global/config/ShedLockConfig.java
  src/main/java/oncog/cogroom/global/infra/prometheus/alertmanager.yml
  src/main/java/oncog/cogroom/global/infra/prometheus/prometheus.yml
  src/main/java/oncog/cogroom/global/infra/prometheus/rules.yml
  src/main/resources/application.yml
Labels: 🔥release
